apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd
  annotations:
    github.com/project-slug: zeeshanAliMedlari/argocd
spec:
  type: other
  lifecycle: unknown
  owner: guests
